# File generated by the below Authors, DO NOT CHANGE.
# This file name all the contributors to this repository.
# See generate authors to make modifications.

Shadrack Awuor
ShadrackAwuor <Dintoz254@gmail.com>

Terrance Ndlangamandla
TerranceNdlangamandla <terrance.sabelo@gmail.com>
